name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.cfat_9hNiKVFfEWUCpvVyl1WTK5fhDiW6F2xmLWxLlImlfd5058fd  }}
          accountId: ${{ secrets.c7488f7bedaeea6c36693a940e5a1431 }}
          projectName: channel4me-frontend
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
